class_name Spawner3D extends Area3D

@export_group("Spawn Settings")
## The PackedScene of the object or enemy that the spawner will instantiate.
@export var scene_to_spawn: PackedScene

## The maximum number of active units generated by this spawner simultaneously.
@export var max_units: int = 5

## The time interval (in seconds) between each spawn. If set to 0.0, spawn only happens once at the start.
@export var respawn_time: float = 5.0

@export_group("References")
## The node defining the geometric shape of the spawn area (must be a CollisionShape3D).
@export var spawn_shape: CollisionShape3D

var _spawned_units: Array[Node] = []
var _timer: Timer

signal spawned(instance: Node)


func _ready() -> void:
	if respawn_time > 0:
		_timer = Timer.new()
		_timer.wait_time = respawn_time
		_timer.timeout.connect(_on_timer_timeout)
		add_child(_timer)
		_timer.start()


func spawn() -> Node:
	if not scene_to_spawn: return null
	
	# Limpar referências inválidas (ex: inimigo derrotado)
	_spawned_units = _spawned_units.filter(func(u): return is_instance_valid(u))
	
	if _spawned_units.size() >= max_units:
		return null
	
	var instance = scene_to_spawn.instantiate()
	get_tree().current_scene.add_child(instance)
	
	# Definir a posição aleatória dentro do shape configurado
	instance.global_position = _get_random_spawn_position()
	
	_spawned_units.append(instance)
	spawned.emit(instance)
	return instance


func _on_timer_timeout() -> void:
	spawn()


func _get_random_spawn_position() -> Vector3:
	if not spawn_shape:
		print("[Spawner3D] spawn_shape não está atribuído! Usando global_position: ", global_position)
		return global_position
		
	if not spawn_shape.shape:
		print("[Spawner3D] spawn_shape não possui recurso de Shape atribuído!")
		return global_position
		
	var shape = spawn_shape.shape
	print("[Spawner3D] Detetado CollisionShape3D com shape: ", shape.get_class())
	if shape is BoxShape3D:
		var size = shape.size
		var local_pos = Vector3(
			randf_range(-size.x / 2.0, size.x / 2.0),
			randf_range(-size.y / 2.0, size.y / 2.0),
			randf_range(-size.z / 2.0, size.z / 2.0)
		)
		var global_pos = spawn_shape.global_transform * local_pos
		print("[Spawner3D] Posição gerada (Box): Local ", local_pos, " -> Global ", global_pos)
		return global_pos
	elif shape is SphereShape3D:
		var radius = shape.radius
		var dir = Vector3(
			randf_range(-1.0, 1.0),
			randf_range(-1.0, 1.0),
			randf_range(-1.0, 1.0)
		).normalized()
		var r = (randf() ** (1.0 / 3.0)) * radius
		var global_pos = spawn_shape.global_transform * (dir * r)
		print("[Spawner3D] Posição gerada (Esfera): -> Global ", global_pos)
		return global_pos
	elif shape is CylinderShape3D:
		var radius = shape.radius
		var height = shape.height
		var angle = randf() * TAU
		var r = sqrt(randf()) * radius
		var local_pos = Vector3(
			cos(angle) * r,
			randf_range(-height / 2.0, height / 2.0),
			sin(angle) * r
		)
		var global_pos = spawn_shape.global_transform * local_pos
		print("[Spawner3D] Posição gerada (Cilindro): Local ", local_pos, " -> Global ", global_pos)
		return global_pos
				
	print("[Spawner3D] Shape não suportado! Usando global_position: ", global_position)
	return global_position
