@icon("./spawner.svg")
class_name Spawner2D extends Area2D

@export_group("Spawn Settings")
## The PackedScene of the object or enemy that the spawner will instantiate.
@export var scene_to_spawn: PackedScene

## The maximum number of active units generated by this spawner simultaneously.
@export var max_units: int = 5

## The time interval (in seconds) between each spawn. If set to 0.0, spawn only happens once at the start.
@export var respawn_time: float = 5.0

@export_group("References")
## The node defining the geometric shape of the spawn area (can be a CollisionShape2D or CollisionPolygon2D).
@export var spawn_shape: Node2D

var _spawned_units: Array[Node] = []
var _timer: Timer

signal spawned(instance: Node)


func _ready() -> void:
	if respawn_time > 0:
		_timer = Timer.new()
		_timer.wait_time = respawn_time
		_timer.timeout.connect(_on_timer_timeout)
		add_child(_timer)
		_timer.start()


func spawn() -> Node:
	if not scene_to_spawn: return null
	
	# Limpar referências inválidas (ex: inimigo derrotado)
	_spawned_units = _spawned_units.filter(func(u): return is_instance_valid(u))
	
	if _spawned_units.size() >= max_units:
		return null
	
	var instance = scene_to_spawn.instantiate()
	get_tree().current_scene.add_child(instance)
	
	# Definir a posição aleatória dentro do shape configurado
	instance.global_position = _get_random_spawn_position()
	
	_spawned_units.append(instance)
	spawned.emit(instance)
	print("Spawned Entity: ", instance)
	return instance


func _on_timer_timeout() -> void:
	spawn()


func _get_random_spawn_position() -> Vector2:
	if not spawn_shape:
		print("[Spawner2D] spawn_shape não está atribuído! Usando global_position: ", global_position)
		return global_position
		
	if spawn_shape is CollisionShape2D and spawn_shape.shape:
		var shape = spawn_shape.shape
		print("[Spawner2D] Detetado CollisionShape2D com shape: ", shape.get_class())
		if shape is RectangleShape2D:
			var size = shape.size
			var local_pos = Vector2(
				randf_range(-size.x / 2.0, size.x / 2.0),
				randf_range(-size.y / 2.0, size.y / 2.0)
			)
			var global_pos = spawn_shape.global_transform * local_pos
			print("[Spawner2D] Posição gerada (Retângulo): Local ", local_pos, " -> Global ", global_pos)
			return global_pos
		elif shape is CircleShape2D:
			var radius = shape.radius
			var angle = randf() * TAU
			var r = sqrt(randf()) * radius
			var local_pos = Vector2(cos(angle), sin(angle)) * r
			var global_pos = spawn_shape.global_transform * local_pos
			print("[Spawner2D] Posição gerada (Círculo): Local ", local_pos, " -> Global ", global_pos)
			return global_pos
	elif spawn_shape is CollisionPolygon2D:
		var global_pos = _get_random_point_in_polygon(spawn_shape)
		print("[Spawner2D] Detetado CollisionPolygon2D. Posição gerada: ", global_pos)
		return global_pos
			
	print("[Spawner2D] Shape não suportado ou inválido! Usando global_position: ", global_position)
	return global_position


func _get_random_point_in_polygon(polygon_node: CollisionPolygon2D) -> Vector2:
	var points = polygon_node.polygon
	if points.is_empty():
		return polygon_node.global_position
		
	# Calcular a bounding box
	var min_x = points[0].x
	var max_x = points[0].x
	var min_y = points[0].y
	var max_y = points[0].y
	for p in points:
		min_x = min(min_x, p.x)
		max_x = max(max_x, p.x)
		min_y = min(min_y, p.y)
		max_y = max(max_y, p.y)
		
	# Tentar gerar uma coordenada interna
	for i in range(100):
		var rand_pt = Vector2(randf_range(min_x, max_x), randf_range(min_y, max_y))
		if Geometry2D.is_point_in_polygon(rand_pt, points):
			return polygon_node.global_transform * rand_pt
			
	return polygon_node.global_transform * points[0]
